# Generated by Django 3.2.7 on 2021-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('newsid', models.IntegerField(db_column='newsId')),
            ],
            options={
                'db_table': 'cookies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('news', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'db_table': 'komentari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('tip', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'korisnici',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lajkovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('commentid', models.IntegerField(db_column='commentId')),
            ],
            options={
                'db_table': 'lajkovi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'vesti',
                'managed': False,
            },
        ),
    ]
